package icu.sett.springmvc.dao;

import icu.sett.springmvc.bean.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 13 11:42:00 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 13 11:42:00 CST 2021
     */
    List<User> selectAll();
}